// SPDX-FileCopyrightText: 2021 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= Changelog for asciidoctor-go
Shulhan <ms@kilabit.info>
21 February 2022
:toc:
:sectanchors:
:sectlinks:

== asciidoctor-go v0.2.0 (2022-03-04)

This release changes the license of asciidoctor-go from BSD to GPL 3.0 or
later.

=== Bug fixes

*  all: fix list check box text get cut one character
+
--
Given the following asciidoc check box markup,

	* [ ] abc

It will rendereded as "&#10063; bc" instead of "&#10063; abc".
--

=== Chores

*  all: replace bytes.Title and strings.Title with function
+
Both of those functions has been deprecated.
+
Since the Title function is to convert the adminition string into a
human title (first letter uppercase), we can use a function to do that.
Any unknown admonition will be returned as is.


== asciidoctor-go v0.1.1 (2021-12-06)

=== Bug fixes

*  all: fix parsing and rendering cross reference

   Previously, when parsing cross reference we assume that if the string
   contains upper-case letter then it's a label so we store it as title
   to search for ID later.

   The bug is when ID is set manually and its contains upper-case for
   example "[#Id]".

   This changes fix this issue by storing cross reference first, not
   assuming it as ID or title, and then when doing rendering we check
   whether its ID or title.

*  all: allow colon ':' and  period '.' on the ID

   According to XML spec [1], the colon is allowed as the first and the next
   character.  While period is only allowed on the next characters.

   [1] https://www.w3.org/TR/REC-xml/#NT-Name


== asciidoctor-go v0.1.0 (2021-03-06)

The asciidoctor-go is the Go module to parse the AsciiDoc (TM) markup
and convert it into HTML5.

This first release bring almost all AsciiDoc syntax except for include
directive, inter-document cross-reference, macros, and non-primary syntax
features.

I hope this library can be useful for Gophers who need the power of AsciiDoc
in their workflows.
