'\" t
.\"     Title: asciidoctor-go
.\"    Author: John Doe
.\" Generator: Asciidoctor 2.0.18
.\"      Date: 2022-12-15
.\"    Manual: ASCIIDOCTOR-GO
.\"    Source: ASCIIDOCTOR-GO
.\"  Language: English
.\"
.TH "ASCIIDOCTOR\-GO" "7" "2022-12-15" "ASCIIDOCTOR\-GO" "ASCIIDOCTOR\-GO"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
asciidoctor-go \- the Go module to parse the AsciiDoc markup.
.SH "SYNOPSIS"
.sp
\fBasciidoctor\-go\fP [\fIOPTION\fP]... \fIFILE\fP...
.SH "ORDERED LIST"
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Item 1.
.sp
Description for item 1.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Item 2
.sp
Literal block inside Item 2,
.sp
.if n .RS 4
.nf
.fam C
Literal block.
.fam
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
Item 3
.sp
Unordered list inside item 3,
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Sub item 3.1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Sub item 3.2
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 4." 4.2
.\}
Item 4
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Item 4.1
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Item 4.2
.RE
.RE
.SH "UNORDERED LIST"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 1.
.sp
Description for item 1.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 2
.sp
Literal block inside Item 2,
.sp
.if n .RS 4
.nf
.fam C
Literal block.
.fam
.fi
.if n .RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 3
.sp
Ordered list inside unordered item 3,
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Sub item 3.1
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Sub item 3.2
.RE
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 4
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 4.1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Item 4.2
.RE
.RE
.SH "DESCRIPTION LIST"
.sp
Item 1
.RS 4
.sp
Description for item 1.
.RE
.sp
Item 2
.RS 4
.sp
Literal block inside Item 2,
.sp
.if n .RS 4
.nf
.fam C
Literal block.
.fam
.fi
.if n .RE
.RE
.sp
Item 3
.RS 4
.sp
Unordered list inside item 3,
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Sub item 3.1
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
Sub item 3.2
.RE
.RE
.SH "AUTHOR"
.sp
John Doe