// SPDX-FileCopyrightText: 2022 M. Shulhan <ms@kilabit.info>
// SPDX-License-Identifier: GPL-3.0-or-later
= roff document type
Shulhan <ms@kilabit.info>
10 Oct 2022
:toc:
:sectlinks:
:man_groff: https://www.gnu.org/software/groff/manual/groff.html
:man_groff_char: https://man7.org/linux/man-pages/man7/groff_char.7.html
:man_pages: https://man7.org/linux/man-pages/man7/man-pages.7.html
:man_roff: https://man7.org/linux/man-pages/man7/roff.7.html

{man_roff}[roff]
is document processor,
its contains text to be printed, how to print it (request, escape), can store
and read variable (_register_).
It commonly use for writing UNIX manual page as we know today.

This notes contains reverse engineering the roff document format by running
the asciidoctor program using backend `manpage`.

== Introduction

roff document is processed line by line.
In most document you will see dot (`.`), acute accent (`'), and backslash
(`\\`).
Dot and acute accent is a control character, always start on new line.
Dot cause a break while acute accent is not.
A break for example is moving the cursor to new line.
Backslash is control character that can be placed anywhere inside a line.


== Reverse engineering

The adoc source for reverse engineering can be viewed at
`testdata/man_backend/test.adoc`, which generated to man page using the
following command,

----
$ asciidoctor --backend=manpage \
	--out-file=testdata/man_backend/test.exp.7 \
	testdata/man_backend/test.adoc
----

===  Header

Lets start from the top.

----
'\" t
.\"     Title: asciidoctor-go
.\"    Author: John Doe
.\" Generator: Asciidoctor 2.0.17
.\"      Date: 2022-10-16
.\"    Manual: ASCIIDOCTOR-GO
.\"    Source: ASCIIDOCTOR-GO
.\"  Language: English
.\"
----

``'\\" t` is a groff {man_groff}#Preprocessors-in-man-pages[syntax
to load preprocessor],
in this case `t` (short name for `gtbl` preprocessor, macro for processing
table).

`.\\"` is a request for line comment.


The next line is,

----
.TH "ASCIIDOCTOR\-GO" "7" "2022-10-16" "ASCIIDOCTOR\-GO" "ASCIIDOCTOR\-GO"
----

`.TH` => {man_groff}#Man-usage[macro to set the title].
See {man_pages}[man-pages(7)] for more information of each argument.


Next,

----
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
----

`.ie` => conditional for if-and-else, `.el` is the conditional for else.

`\\n` => {man_groff}#Interpolating-Registers[get value of numeric register].
in this case the register name is `.g`, which is 1 if running under GNU troff.

`.ds` => set string register, in this case to set register `Aq` with `\\(aq`.

`\\(aq` => {man_groff}#Glyph-Name-Index[get glyph symbol] for `aq`,
which is equal to `\'` ({man_groff_char}[neutral aposthrope]).

So, the above if-else can be translated to

----
IF run-using(groff)==1 THEN SET Aq \(aq
ELSE SET Aq '
----
		
Next,

----
.ss \n[.ss] 0
.nh
.ad l
----

`.ss` => set size of a space between words to value of register `.ss` and a
space between sentence to 0.

`.nh` => disable hyphenation.

`.ad l` => Adjust text to the left margin.
This produces what is traditionally called ragged-right text.

Next,

----
.de URL
\fI\\$2\fP <\\$1>\\$3
..
----

`.de` => {man_groff}#Writing-Macros[create macro] named URL, with content in
the next line.

`..` => the end of macro.

`\\fI` => change the font mode to `I` (italic).

`\\$2` => get the second macro argument, in that case `\\$1` is the first
argument and `\\$3` is the third argument.

`\\fP` => switch to previous font mode.

Next,

----
.als MTO URL
----

`.als` => set alias `MTO` for macro `URL`.


Next,

----
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
----

`.if \\n[.g]` => 1 (true) if document run under groff.

`.mso www.tmac` => include file `www.tmac` from the same directory as macro
files.

`.am URL` => extend the macro `URL` by adding `.ad l`

`.am MTO` => extend the macro `MTO` by adding `.ad l`

`.LINKSTYLE blue R < >` => This is from the document attributes
`:man-linkstyle:`.

This end the "header" of man page generated by asciidoctor.


=== Section and subsections

----
.SH "NAME"
asciidoctor-go \- the Go module to parse the AsciiDoc markup.
----

`.SH "NAME"` => Write section header with title "NAME".

Section level 2 always have title in uppercase.

Subsection with level 3 and above are written with

----
.SS "<title>"
----

=== Ordered list

----
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Item 1.
.sp
Description for item 1.
.RE
----

`.sp` => insert one new line.

`.RS 4` => Move the left margin to the right by `4` n unit (n = half of m)

`.RE` => Restore the previous left margin.

`.ie n` => True if {man_groff}#Troff-and-Nroff-Mode[running under `nroff`].

`\\{\\` `\\}` => used in if-else condition.

`.\\h'xxx'` => Move cursor horizontally `xxx` m (ems, approximately equal to
the width of letter `m`) unit.
Negative means moving backward, positive means moving forward.

`.IP " 1." 4.2` => set up indented paragraph, with string " 1." as designator
and indentation width is `4.2 n`.

`\\c` => continue a line, anything after it will be ignored.

===  Inline markup

`\\fB` => change font mode to `B` (bold).

`\\fP` => change to the previous font mode.

===  Escaped characters

List of characters must be escaped,

`-` => `\\-`, only if its not wrapped by letters.


== References

[1] {man_roff}[roff manual page].

[2] https://docs.asciidoctor.org/asciidoctor/latest/manpage-backend/[Generate
Manual Pages from AsciiDoc^]

[3] http://n-t-roff.github.io/heirloom/doctools/troff.pdf[Nroff/Troff User’s
Manual].

[4] {man_groff}[The GNU Troff Manual].

[5] {man_pages}

[6] {man_groff_char}
